# 
# Do not Edit! Generated by:
# spectacle version 0.15
# 
# >> macros
# << macros

Name:       evtest
Summary:    Event device test program
Version:    1.33
Release:    0
Group:      System/Hardware Support
License:    GPLv2+
URL:        http://cgit.freedesktop.org/evtest/
Source100:  evtest.yaml
BuildRequires:  automake libxml2-devel automake
# asciidoc xmlto 

%description
Description: %{name} is a simple utility to query information about input devices
and watch the event stream generated by input devices.

%prep
%setup -q

# >> setup
# << setup

%build
# >> build pre
autoreconf -v --install || exit 1
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/%{name}
%{_bindir}/evtest-capture
%doc COPYING
#%{_mandir}/man1/evtest.1*
#%{_mandir}/man1/evtest-capture.1*
%{_datadir}/%{name}/evtest-create-device.xsl
# << files


